-- AlterTable
ALTER TABLE "User" ADD COLUMN "levelChoice" TEXT NOT NULL DEFAULT 'N5';
ALTER TABLE "User" ADD COLUMN "focusSkill" TEXT NOT NULL DEFAULT 'BALANCED';
ALTER TABLE "User" ADD COLUMN "learningStyle" TEXT NOT NULL DEFAULT 'STRUCTURED';
